tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

cask "alacritty"
brew "asdf"
brew "git"
brew "gnupg"
brew "watch"

cask "appcleaner"
cask "brave-browser"
cask "docker"
cask "fliqlo"
cask "google-backup-and-sync"
cask "menumeters"
cask "spectacle"
cask "visual-studio-code"
