add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$python\
$docker_context\
$kubernetes\
$fill\
$cmd_duration\
$time
$character\
"""

palette = "catppuccin_mocha"

[directory]
style = "cyan"
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = "purple"
format = '[$symbol$branch(:$remote_branch)]($style) '

[nodejs]
style = "green"
format = '[$symbol$version](green) '

[python]
style = "yellow"
format = "[$symbol$version]($style) "

[docker_context]
style = "blue"
format = '[$symbol$context]($style) '

[kubernetes]
style = "blue"
symbol = " "
format = '[$symbol$context]($style) '
detect_files = ['.k8s']
disabled = false

[fill]
style = "black"
symbol = " "

[cmd_duration]
format = " in $duration "
min_time = 0

[time]
style = "yellow"
format = '[ $time]($style) '
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"