set -g mouse on
set -g default-terminal "tmux-256color"

bind-key -n C-M-v split-window -v
bind-key -n C-M-h split-window -h

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# clone TPM plugin repo git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# install plugins with `prefix + I (capital i, as in Install)`
run '~/.tmux/plugins/tpm/tpm'
